# Generated by Django 2.1.5 on 2019-02-09 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField(default=None)),
                ('date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'db_table': 'answer',
            },
        ),
        migrations.CreateModel(
            name='CommentExpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=250)),
                ('date', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.AnswerModel')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'comment',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='GradeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'grade',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default=None, max_length=50)),
                ('tooltip', models.TextField(default=None, max_length=350, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.CourseModel')),
            ],
            options={
                'db_table': 'question',
            },
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default=None, max_length=20)),
                ('name', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'stage',
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.StageModel'),
        ),
        migrations.AddField(
            model_name='commentexpmodel',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.GradeModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.GradeModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.QuestionModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
