# Generated by Django 2.1.5 on 2019-01-29 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.NullBooleanField(default=None)),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='CommentExpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(default=None, max_length=250)),
                ('date', models.DateTimeField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.AnswerModel')),
            ],
            options={
                'db_table': 'comments',
            },
        ),
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='GradesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(default=None, max_length=20)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='QuestionModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qestion', models.CharField(default=None, max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.CourseModel')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='StageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part', models.CharField(default=None, max_length=20)),
                ('stage', models.CharField(default=None, max_length=50)),
            ],
            options={
                'db_table': 'stages',
            },
        ),
        migrations.CreateModel(
            name='UserDataModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=30)),
                ('last', models.CharField(default=None, max_length=30)),
                ('age', models.PositiveSmallIntegerField()),
                ('email', models.CharField(default=None, max_length=30)),
                ('date', models.DateTimeField(verbose_name='date')),
            ],
            options={
                'db_table': 'usersdata',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default=None, max_length=30)),
                ('password', models.CharField(default=None, max_length=30)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.RoleModel')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='formapp.UserDataModel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='stage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formapp.StageModel'),
        ),
        migrations.AddField(
            model_name='commentexpmodel',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.UserModel'),
        ),
        migrations.AddField(
            model_name='commentexpmodel',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.GradesModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='grade',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.GradesModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.QuestionModel'),
        ),
        migrations.AddField(
            model_name='answermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.UserModel'),
        ),
    ]
