# Generated by Django 2.1.5 on 2019-01-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='questionmodel',
            old_name='qestion',
            new_name='question',
        ),
        migrations.AddField(
            model_name='questionmodel',
            name='tooltip',
            field=models.CharField(default=None, max_length=350),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='age',
            field=models.PositiveSmallIntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='userdatamodel',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
