# Generated by Django 2.1.5 on 2019-01-30 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0003_auto_20190130_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
