# Generated by Django 2.1.5 on 2019-01-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0004_auto_20190130_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='question',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='tooltip',
            field=models.TextField(default=None, max_length=350),
        ),
    ]
