# Generated by Django 2.1.5 on 2019-01-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0005_auto_20190130_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='tooltip',
            field=models.TextField(default=None, max_length=350, null=True),
        ),
    ]
