# Generated by Django 2.1.5 on 2019-02-01 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0006_auto_20190130_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentexpmodel',
            old_name='comment',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='coursemodel',
            old_name='course',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='gradesmodel',
            old_name='grade',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='questionmodel',
            old_name='question',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='rolemodel',
            old_name='role',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='stagemodel',
            old_name='part',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='stagemodel',
            old_name='stage',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='grade',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formapp.GradesModel'),
        ),
    ]
