# Generated by Django 2.1.5 on 2019-02-01 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0007_auto_20190201_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GradesModel',
            new_name='GradeModel',
        ),
    ]
