# Generated by Django 2.1.5 on 2019-02-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0008_auto_20190201_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='date',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
