# Generated by Django 2.1.5 on 2019-02-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0009_auto_20190204_2323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usermodel',
            name='role',
        ),
        migrations.AlterField(
            model_name='answermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.UserModel'),
        ),
        migrations.AlterField(
            model_name='commentexpmodel',
            name='expert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='authapp.UserModel'),
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
        migrations.DeleteModel(
            name='UserDataModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
