# Generated by Django 2.1.5 on 2019-02-09 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolemodel',
            table='role',
        ),
    ]
