# Generated by Django 2.1.5 on 2019-02-09 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_auto_20190209_1506'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='rolemodel',
            table='roles',
        ),
    ]
