# Generated by Django 2.1.5 on 2019-02-09 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('authapp', '0003_auto_20190209_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdatamodel',
            name='auth_django',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='auth_django',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
